import test from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { JSON_CONTRACT_VERSION, main } from "../src/cli/index.js";
import { generateCapsule } from "../src/core/capsule.js";
import { initWorkspace, ORANGE_GITIGNORE, ROOT_GITIGNORE_REQUIRED_LINES, readConfig } from "../src/core/config.js";
import { stringifyFrontmatter } from "../src/core/frontmatter.js";
import { runDoctor } from "../src/core/doctor.js";
import {
  acceptMemoryDelta,
  listMemoryGraphNodes,
  proposeMemoryDelta,
  readMemoryDeltaProposalFile,
  rejectMemoryDelta,
  reviseMemoryDeltaProposal
} from "../src/core/memory.js";
import { workspacePaths } from "../src/core/paths.js";
import { completeQuest, createQuest, listQuests, readQuestFile } from "../src/core/quest.js";

const ORANGE_BIN = new URL("../bin/orange.js", import.meta.url);

function tempWorkspace() {
  return fs.mkdtempSync(path.join(os.tmpdir(), "orange-hyper-test-"));
}

function assertOrangeGitignorePolicy(source) {
  const lines = source.trimEnd().split(/\r?\n/);
  for (const expected of ORANGE_GITIGNORE.trimEnd().split("\n")) {
    assert.ok(lines.includes(expected), `.orange-hyper/.gitignore should include ${expected}`);
  }
  assert.equal(lines.includes("proposals/"), false);
  assert.equal(lines.includes("/proposals/"), false);
}

function assertIndependentGitignoreLines(source, expectedLines, label) {
  const lines = source.trimEnd().split(/\r?\n/);
  for (const expected of expectedLines) {
    assert.ok(lines.includes(expected), `${label} should include independent line ${expected}`);
  }
}

test("init creates the v0.2 storage structure", () => {
  const cwd = tempWorkspace();
  const paths = initWorkspace(cwd, { projectName: "demo" });
  const config = readConfig(cwd);
  assert.ok(fs.existsSync(paths.config));
  assert.ok(fs.existsSync(paths.orangeGitignore));
  assert.ok(fs.existsSync(paths.activeQuests));
  assert.ok(fs.existsSync(paths.completedQuests));
  assert.ok(fs.existsSync(paths.pendingMemoryDeltaProposals));
  assert.ok(fs.existsSync(paths.acceptedMemoryDeltaProposals));
  assert.ok(fs.existsSync(paths.rejectedMemoryDeltaProposals));
  assert.ok(fs.existsSync(paths.graphDecisionNodes));
  assert.ok(fs.existsSync(paths.graphConstraintNodes));
  assert.ok(fs.existsSync(paths.graphComponentNodes));
  assert.ok(fs.existsSync(paths.graphRiskNodes));
  assert.ok(fs.existsSync(paths.graphVerificationNodes));
  assert.ok(fs.existsSync(paths.graphEdges));
  assert.ok(fs.existsSync(paths.graphIndex));
  assert.ok(fs.existsSync(paths.currentCapsule));
  assert.ok(fs.existsSync(paths.routeTrace));
  assert.match(config.project_id, /^project_[0-9a-f-]{36}$/);
  assert.equal(config.origin.source_repository, "https://github.com/KoreanCode/orange-hyper");
  assert.equal(config.project_name, "demo");
  assert.equal(config.project.id, config.project_id);
  assert.equal(config.project.name, "demo");
  assert.doesNotMatch(JSON.stringify(config), new RegExp(escapeRegExp(cwd)));
  const currentCapsule = fs.readFileSync(paths.currentCapsule, "utf8");
  assert.match(currentCapsule, /Generated by: Orange Hyper 0\.4\.0/);
  assert.match(currentCapsule, /Source repository: https:\/\/github\.com\/KoreanCode\/orange-hyper/);
  assert.match(currentCapsule, new RegExp(`Project id: ${escapeRegExp(config.project_id)}`));
  const index = JSON.parse(fs.readFileSync(paths.graphIndex, "utf8"));
  assert.equal(index.index_version, "0.3.0");
  assert.equal(index.project_id, config.project_id);
  assert.deepEqual(index.nodes, []);
  assert.equal(fs.readFileSync(paths.orangeGitignore, "utf8"), ORANGE_GITIGNORE);
  assertOrangeGitignorePolicy(fs.readFileSync(paths.orangeGitignore, "utf8"));
});

test("init is idempotent and preserves existing quest and trace files", () => {
  const cwd = tempWorkspace();
  const paths = initWorkspace(cwd);
  const created = createQuest(cwd, "keep this quest", {
    clock: new Date("2026-06-16T00:00:00.000Z")
  });
  fs.appendFileSync(paths.routeTrace, `${JSON.stringify({ trace_id: "route_keep", contract: { route: "L2/P2/T2/V2/A0/M0/MB2" } })}\n`);
  const projectId = readConfig(cwd).project_id;
  initWorkspace(cwd);
  assert.ok(fs.existsSync(created.filePath));
  assert.match(fs.readFileSync(paths.routeTrace, "utf8"), /route_keep/);
  assert.equal(readConfig(cwd).project_id, projectId);
});

test("init upgrades legacy proposal ignore policy without overwriting config or shared memory", () => {
  const cwd = tempWorkspace();
  const paths = initWorkspace(cwd);
  const configBefore = fs.readFileSync(paths.config, "utf8");
  const acceptedMemory = path.join(paths.acceptedMemoryDeltaProposals, "mem_delta_shared.md");
  fs.writeFileSync(acceptedMemory, "shared accepted proposal placeholder\n");
  fs.writeFileSync(
    paths.orangeGitignore,
    [
      "capsules/",
      "traces/",
      "proposals/",
      "identity/",
      "local/",
      "custom-local/",
      ""
    ].join("\n")
  );

  initWorkspace(cwd);

  assert.equal(fs.readFileSync(paths.config, "utf8"), configBefore);
  assert.equal(fs.readFileSync(acceptedMemory, "utf8"), "shared accepted proposal placeholder\n");
  const gitignore = fs.readFileSync(paths.orangeGitignore, "utf8");
  assertOrangeGitignorePolicy(gitignore);
  assert.ok(gitignore.trimEnd().split(/\r?\n/).includes("custom-local/"));
});

test("init policy keeps accepted proposals shareable while local state stays ignored", () => {
  assertOrangeGitignorePolicy(ORANGE_GITIGNORE);
  for (const localPath of [
    "capsules/",
    "traces/",
    "identity/",
    "local/",
    "hooks/reports/",
    "proposals/memory-delta/pending/",
    "proposals/memory-delta/rejected/"
  ]) {
    assert.ok(ORANGE_GITIGNORE.includes(`${localPath}\n`));
  }
  assert.equal(ORANGE_GITIGNORE.includes("proposals/memory-delta/accepted/"), false);
});

test("repository gitignore files keep public memory policy as independent lines", () => {
  assertIndependentGitignoreLines(
    fs.readFileSync(path.join(process.cwd(), ".gitignore"), "utf8"),
    ROOT_GITIGNORE_REQUIRED_LINES,
    "root .gitignore"
  );
  assertOrangeGitignorePolicy(fs.readFileSync(path.join(process.cwd(), ".orange-hyper", ".gitignore"), "utf8"));
});

test("gitignore policy ignores local state while accepted memory and graph stay shareable", () => {
  const cwd = tempWorkspace();
  fs.writeFileSync(path.join(cwd, ".gitignore"), `${ROOT_GITIGNORE_REQUIRED_LINES.join("\n")}\n`);
  initWorkspace(cwd);
  const init = spawnSync("git", ["init"], { cwd, encoding: "utf8" });
  assert.equal(init.status, 0);

  for (const localPath of [
    ".orange-hyper/capsules/current.md",
    ".orange-hyper/traces/route.jsonl",
    ".orange-hyper/identity/orange-hyper.html",
    ".orange-hyper/local/state.json",
    ".orange-hyper/hooks/reports/hook-run-stop.json",
    ".orange-hyper/proposals/memory-delta/pending/example.md",
    ".orange-hyper/proposals/memory-delta/rejected/example.md"
  ]) {
    assertGitIgnored(cwd, localPath, true);
  }
  for (const publicPath of [
    ".orange-hyper/config.json",
    ".orange-hyper/quests/completed/example.md",
    ".orange-hyper/proposals/memory-delta/accepted/example.md",
    ".orange-hyper/graph/index.json"
  ]) {
    assertGitIgnored(cwd, publicPath, false);
  }
});

test("init backfills missing v0.2/v0.3 storage without overwriting legacy config identity", () => {
  const cwd = tempWorkspace();
  const paths = workspacePaths(cwd);
  fs.mkdirSync(paths.root, { recursive: true });
  fs.writeFileSync(paths.config, `${JSON.stringify({
    version: "0.1.0",
    project: {
      name: "legacy-demo",
      default_language: "ko"
    },
    features: {
      hooks: false,
      mcp: false,
      subagents: false,
      auto_execution_loop: false
    }
  }, null, 2)}\n`);

  initWorkspace(cwd);
  const unchanged = JSON.parse(fs.readFileSync(paths.config, "utf8"));
  assert.equal(unchanged.project_id, undefined);
  assert.equal(unchanged.project?.id, undefined);
  assert.equal(unchanged.project?.name, "legacy-demo");
  assert.ok(fs.existsSync(paths.pendingMemoryDeltaProposals));
  assert.ok(fs.existsSync(paths.acceptedMemoryDeltaProposals));
  assert.ok(fs.existsSync(paths.rejectedMemoryDeltaProposals));
  assert.ok(fs.existsSync(paths.graphDecisionNodes));
  assert.ok(fs.existsSync(paths.graphConstraintNodes));
  assert.ok(fs.existsSync(paths.graphComponentNodes));
  assert.ok(fs.existsSync(paths.graphRiskNodes));
  assert.ok(fs.existsSync(paths.graphVerificationNodes));
  assert.ok(fs.existsSync(paths.graphIndex));
  assert.ok(fs.existsSync(paths.graphEdges));

  const beforeRepair = runDoctor(cwd);
  assert.equal(beforeRepair.ok, false);
  assert.equal(beforeRepair.diagnostics.errors.some((item) => item.code === "CONFIG_PROJECT_ID_MISSING"), true);

  const repaired = runDoctor(cwd, { repairProjectId: true });
  assert.equal(repaired.ok, true);
  assert.equal(repaired.diagnostics.repairs.some((item) => item.code === "CONFIG_PROJECT_ID_REPAIRED"), true);
  const repairedConfig = readConfig(cwd);
  assert.match(repairedConfig.project_id, /^project_[0-9a-f-]{36}$/);
  assert.equal(repairedConfig.project.id, repairedConfig.project_id);
  assert.equal(repairedConfig.project.name, "legacy-demo");
});

test("quest lifecycle writes markdown frontmatter, capsule, completion evidence, and doctor passes", () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  const config = readConfig(cwd);

  const created = createQuest(cwd, "implement the route contract formatter", {
    clock: new Date("2026-06-16T00:00:00.000Z"),
    expectedVerification: ["node --test"]
  });
  assert.equal(created.data.project_id, config.project_id);
  assert.equal(created.data.project_name, config.project_name);
  assert.ok(fs.readFileSync(created.filePath, "utf8").startsWith("---\n"));
  assert.equal(listQuests(cwd, "active").length, 1);

  const capsule = generateCapsule(cwd, created.id, {
    clock: new Date("2026-06-16T00:01:00.000Z")
  });
  assert.match(capsule.content, /Orange Hyper Current Capsule/);
  assert.match(capsule.content, /Generated by: Orange Hyper 0\.4\.0/);
  assert.match(capsule.content, /Source repository: https:\/\/github\.com\/KoreanCode\/orange-hyper/);
  assert.match(capsule.content, /## Project Boundary/);
  assert.match(capsule.content, new RegExp(`Project id: ${escapeRegExp(config.project_id)}`));
  assert.match(capsule.content, /Only Quest, Proposal, and Accepted Node artifacts with this project_id are project memory/);
  assert.match(capsule.content, /external project docs/);
  assert.ok(fs.existsSync(workspacePaths(cwd).currentCapsule));

  const completed = completeQuest(cwd, created.id, {
    clock: new Date("2026-06-16T00:02:00.000Z"),
    evidence: ["node --test passed"]
  });
  assert.equal(completed.data.status, "completed");
  assert.equal(completed.data.project_id, config.project_id);
  assert.equal(completed.data.verification_status, "verified");
  assert.equal(listQuests(cwd, "active").length, 0);
  assert.equal(listQuests(cwd, "completed").length, 1);

  const doctor = runDoctor(cwd);
  assert.deepEqual(doctor.errors, []);
  assert.equal(doctor.ok, true);
});

test("quest completion requires evidence or unverified reason", () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  const created = createQuest(cwd, "implement a bounded feature", {
    clock: new Date("2026-06-16T00:00:00.000Z")
  });
  assert.throws(() => completeQuest(cwd, created.id), /requires --evidence or --unverified/);
});

test("completed quest cannot be completed twice", () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  const created = createQuest(cwd, "ship a small hardening fix", {
    clock: new Date("2026-06-16T00:00:00.000Z")
  });
  completeQuest(cwd, created.id, {
    clock: new Date("2026-06-16T00:01:00.000Z"),
    unverifiedReason: "Manual verification is not available in seed test"
  });
  assert.throws(
    () => completeQuest(cwd, created.id, { unverifiedReason: "again" }),
    /already completed/
  );
});

test("unverified completion records unverified status and reason", () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  const created = createQuest(cwd, "document unverified completion", {
    clock: new Date("2026-06-16T00:00:00.000Z")
  });
  const completed = completeQuest(cwd, created.id, {
    clock: new Date("2026-06-16T00:01:00.000Z"),
    unverifiedReason: "Manual verification is not available in seed test"
  });
  assert.equal(completed.data.status, "completed");
  assert.equal(completed.data.verification_status, "unverified");
  assert.equal(completed.data.unverified_reason, "Manual verification is not available in seed test");
});

test("quest done merges inline evidence and evidence-file into verified completion", async () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  const created = createQuest(cwd, "complete with evidence file", {
    clock: new Date("2026-06-16T00:00:00.000Z")
  });
  const evidencePath = path.join(cwd, "verification.txt");
  fs.writeFileSync(evidencePath, "npm test passed\nCLI smoke passed\n");
  await main(["quest", "done", created.id, "--evidence", "git diff --check passed", "--evidence-file", "verification.txt"], {
    cwd,
    io: silentIo()
  });
  const completed = listQuests(cwd, "completed")[0];
  assert.equal(completed.data.status, "completed");
  assert.equal(completed.data.verification_status, "verified");
  assert.deepEqual(completed.data.verification_evidence, ["git diff --check passed", "npm test passed\nCLI smoke passed"]);
});

test("quest done rejects evidence and unverified together", async () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  const created = createQuest(cwd, "reject conflicting completion state", {
    clock: new Date("2026-06-16T00:00:00.000Z")
  });
  await assert.rejects(
    () => main(["quest", "done", created.id, "--evidence", "npm test passed", "--unverified", "not checked"], { cwd, io: silentIo() }),
    /cannot combine verification evidence with --unverified/
  );
});

test("route --quest preserves the quest layer unless explicitly overridden", async () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  const created = createQuest(cwd, "implement a multi-step capsule feature", {
    layer: "L3",
    clock: new Date("2026-06-16T00:00:00.000Z")
  });
  const output = [];
  const io = {
    stdout: { write: (chunk) => output.push(chunk) },
    stderr: { write: () => {} }
  };
  await main(["route", "--quest", created.id], { cwd, io });
  assert.match(output.join(""), /Orange route: L3/);
});

test("quest new prints quest id as its own line and next kernel commands", async () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  const { output, io } = captureIo();
  await main(["quest", "new", "implement seed kernel output hardening"], { cwd, io });
  const quest = listQuests(cwd, "active")[0];
  const lines = output.join("").trimEnd().split(/\r?\n/);
  assert.equal(lines[0], `Created quest: ${quest.data.id}`);
  assert.equal(lines[1], `File: .orange-hyper/quests/active/${quest.data.id}.md`);
  assert.ok(lines.includes("Next:"));
  assert.ok(lines.includes(`  orange route --quest ${quest.data.id}`));
  assert.ok(lines.includes(`  orange capsule --quest ${quest.data.id}`));
});

test("quest new --json prints valid JSON without human-readable output", async () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  const { output, io } = captureIo();
  await main(["quest", "new", "--json", "implement JSON quest creation output"], { cwd, io });
  const raw = output.join("");
  const payload = parseJsonOnly(raw);
  assertJsonEnvelope(payload, true, "quest.new");
  assert.match(payload.data.quest.id, /^quest_/);
  assert.equal(payload.data.quest.file, `.orange-hyper/quests/active/${payload.data.quest.id}.md`);
  assert.equal(payload.data.next.route, `orange route --quest ${payload.data.quest.id}`);
  assert.equal(payload.data.next.capsule, `orange capsule --quest ${payload.data.quest.id}`);
  assert.doesNotMatch(raw, /Created quest:/);
  assert.doesNotMatch(raw, /Next:/);
  assert.doesNotMatch(raw, /Orange route:/);
});

test("route --json prints valid JSON without human-readable output", async () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  const created = createQuest(cwd, "implement route JSON output", {
    clock: new Date("2026-06-16T00:00:00.000Z")
  });
  const { output, io } = captureIo();
  await main(["route", "--quest", created.id, "--json"], { cwd, io });
  const raw = output.join("");
  const payload = parseJsonOnly(raw);
  assertJsonEnvelope(payload, true, "route.show");
  assert.equal(payload.data.trace.quest_id, created.id);
  assert.equal(payload.data.trace.contract.route, payload.data.contract.route);
  assert.equal(payload.data.contract.output_contract, created.data.output_contract);
  assert.doesNotMatch(raw, /Output contract:/);
  assert.doesNotMatch(raw, /Quest policy:/);
  assert.doesNotMatch(raw, /Trace:/);
});

test("route trace lines are JSON parseable", async () => {
  const cwd = tempWorkspace();
  const paths = initWorkspace(cwd);
  const created = createQuest(cwd, "implement route trace hardening", {
    clock: new Date("2026-06-16T00:00:00.000Z")
  });
  await main(["route", "--quest", created.id], { cwd, io: silentIo() });
  const lines = fs.readFileSync(paths.routeTrace, "utf8").split(/\r?\n/).filter(Boolean);
  assert.ok(lines.length > 0);
  for (const line of lines) {
    const trace = JSON.parse(line);
    assert.equal(trace.source_repository, "https://github.com/KoreanCode/orange-hyper");
  }
});

test("capsule --quest writes current.md for the selected quest", async () => {
  const cwd = tempWorkspace();
  const paths = initWorkspace(cwd);
  const created = createQuest(cwd, "build selected capsule", {
    clock: new Date("2026-06-16T00:00:00.000Z")
  });
  await main(["capsule", "--quest", created.id], { cwd, io: silentIo() });
  const content = fs.readFileSync(paths.currentCapsule, "utf8");
  assert.match(content, /build selected capsule/);
});

test("capsule --json prints valid JSON without human-readable output", async () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  const created = createQuest(cwd, "build selected JSON capsule", {
    clock: new Date("2026-06-16T00:00:00.000Z")
  });
  const { output, io } = captureIo();
  await main(["capsule", "--quest", created.id, "--json"], { cwd, io });
  const raw = output.join("");
  const payload = parseJsonOnly(raw);
  assertJsonEnvelope(payload, true, "capsule.build");
  assert.equal(payload.data.capsule.file, ".orange-hyper/capsules/current.md");
  assert.equal(payload.data.quest.id, created.id);
  assert.match(payload.data.capsule.content, /build selected JSON capsule/);
  assert.doesNotMatch(raw, /^Wrote /m);
});

test("capsule without quests fails clearly", async () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  await assert.rejects(
    () => main(["capsule"], { cwd, io: silentIo() }),
    /No active quest found/
  );
});

test("path traversal selectors fail for quest-reading commands", async () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  createQuest(cwd, "safe quest", {
    clock: new Date("2026-06-16T00:00:00.000Z")
  });
  const badSelectors = ["../../package.json", "../README.md", "quests/../../package.json"];
  for (const selector of badSelectors) {
    await assert.rejects(() => main(["quest", "show", selector], { cwd, io: silentIo() }), /Quest path must stay inside/);
    await assert.rejects(() => main(["route", "--quest", selector], { cwd, io: silentIo() }), /Quest path must stay inside/);
    await assert.rejects(() => main(["capsule", "--quest", selector], { cwd, io: silentIo() }), /Quest path must stay inside/);
    await assert.rejects(
      () => main(["quest", "done", selector, "--unverified", "not checked"], { cwd, io: silentIo() }),
      /Quest path must stay inside/
    );
  }
});

test("frontmatter subset handles colons quotes Korean empty arrays and lists", () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  const created = createQuest(cwd, '회원가입 정책: "재가입"을 바꿔줘', {
    title: "Policy: signup",
    constraints: ["한글 제약", "quote: keep it"],
    unknowns: ["탈퇴 상태 필드 확인"],
    clock: new Date("2026-06-16T00:00:00.000Z")
  });
  const quest = readQuestFile(created.filePath);
  assert.equal(quest.data.title, "Policy: signup");
  assert.equal(quest.data.scope_paths.length, 0);
  assert.deepEqual(quest.data.constraints, ["한글 제약", "quote: keep it"]);
  assert.deepEqual(quest.data.unknowns, ["탈퇴 상태 필드 확인"]);
  assert.match(quest.body, /"재가입"/);
});

test("doctor catches broken frontmatter", () => {
  const cwd = tempWorkspace();
  const paths = initWorkspace(cwd);
  fs.writeFileSync(path.join(paths.activeQuests, "broken.md"), "# Missing frontmatter\n");
  const result = runDoctor(cwd);
  assert.equal(result.ok, false);
  assert.match(result.errors.join("\n"), /Missing YAML frontmatter/);
});

test("doctor catches completed quests without verification information", () => {
  const cwd = tempWorkspace();
  const paths = initWorkspace(cwd);
  fs.writeFileSync(
    path.join(paths.completedQuests, "bad.md"),
    stringifyFrontmatter(
      {
        schema_version: 1,
        id: "quest_bad",
        title: "Bad quest",
        status: "completed",
        created_at: "2026-06-16T00:00:00.000Z",
        updated_at: "2026-06-16T00:00:00.000Z",
        layer: "L2",
        route: "L2/P2/T2/V2/A0/M0/MB2",
        quest_policy: "recommended",
        output_contract: "implementation",
        scope_paths: [],
        constraints: [],
        unknowns: [],
        expected_verification: [],
        verification_status: "pending",
        verification_evidence: [],
        unverified_reason: ""
      },
      "# Bad quest"
    )
  );
  const result = runDoctor(cwd);
  assert.equal(result.ok, false);
  assert.match(result.errors.join("\n"), /must be verified or unverified/);
  assert.match(result.errors.join("\n"), /needs verification evidence or unverified reason/);
});

test("L0/L1 quest new creates quest but prints not_recommended warning", async () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  const output = [];
  await main(["quest", "new", "왜 Service에 트랜잭션이 있어야 해?"], {
    cwd,
    io: {
      stdout: { write: (chunk) => output.push(chunk) },
      stderr: { write: () => {} }
    }
  });
  assert.equal(listQuests(cwd, "active").length, 1);
  const joined = output.join("");
  assert.match(joined, /Quest policy: not_recommended/);
  assert.match(joined, /A Quest was created because you explicitly requested quest new/);
});

test("remember propose list show accept and reject support JSON envelopes", async () => {
  const cwd = tempWorkspace();
  const paths = initWorkspace(cwd);
  const config = readConfig(cwd);
  const first = createQuest(cwd, "remember a durable implementation decision", {
    layer: "L2",
    clock: new Date("2026-06-16T00:00:00.000Z")
  });
  completeQuest(cwd, first.id, {
    clock: new Date("2026-06-16T00:01:00.000Z"),
    evidence: ["npm test passed"]
  });

  const proposed = assertJsonCommand(
    runOrange(["remember", "propose", "--quest", first.id, "--json"], cwd),
    "remember.propose"
  );
  assert.equal(proposed.data.duplicated, false);
  assert.deepEqual(proposed.data.warnings, []);
  const proposalId = proposed.data.proposal.id;
  assert.equal(proposed.data.proposal.project_id, config.project_id);
  assert.equal(proposed.data.proposal.project_name, config.project_name);
  assert.equal(proposed.data.proposal.source_repository, "https://github.com/KoreanCode/orange-hyper");
  assert.equal(proposed.data.proposal.status, "pending");
  assert.equal(proposed.data.proposal.file, `.orange-hyper/proposals/memory-delta/pending/${proposalId}.md`);

  const listed = assertJsonCommand(runOrange(["remember", "list", "--json"], cwd), "remember.list");
  assert.equal(listed.data.proposals.length, 1);
  assert.equal(listed.data.proposals[0].id, proposalId);

  const shown = assertJsonCommand(runOrange(["remember", "show", proposalId, "--json"], cwd), "remember.show");
  assert.equal(shown.data.proposal.id, proposalId);
  assert.match(shown.data.proposal.body, /## Candidate Memory/);
  assert.match(shown.data.proposal.body, /## Suggested Node/);

  const accepted = assertJsonCommand(runOrange(["remember", "accept", proposalId, "--json"], cwd), "remember.accept");
  assert.equal(accepted.data.proposal.status, "accepted");
  assert.equal(accepted.data.proposal.project_id, config.project_id);
  assert.equal(accepted.data.node.project_id, config.project_id);
  assert.equal(accepted.data.node.project_name, config.project_name);
  assert.equal(accepted.data.node.source_proposal, proposalId);
  assert.equal(accepted.data.node.source_quest, first.id);
  assert.equal(accepted.data.node.node_type, "decision");
  assert.equal(accepted.data.node.origin, "memory-delta-proposal");
  assert.match(accepted.data.node.accepted_at, /^20\d\d-/);
  assert.match(accepted.data.node.source_proposal_hash, /^[a-f0-9]{64}$/);
  assert.equal(accepted.data.node.provenance.proposal_id, proposalId);
  assert.equal(accepted.data.node.provenance.source_proposal, proposalId);
  assert.equal(accepted.data.node.provenance.source_quest, first.id);
  assert.equal(accepted.data.node.provenance.node_type, "decision");
  assert.equal(accepted.data.node.provenance.origin, "memory-delta-proposal");
  assert.equal(accepted.data.node.provenance.project_id, config.project_id);
  assert.equal(accepted.data.node.provenance.project_name, config.project_name);
  assert.equal(accepted.data.node.provenance.source_repository, "https://github.com/KoreanCode/orange-hyper");
  assert.equal(accepted.data.node.provenance.accepted_at, accepted.data.node.accepted_at);
  assert.equal(accepted.data.node.provenance.source_proposal_hash, accepted.data.node.source_proposal_hash);
  assert.ok(fs.existsSync(path.join(paths.acceptedMemoryDeltaProposals, `${proposalId}.md`)));
  assert.equal(runOrange(["remember", "accept", proposalId, "--json"], cwd).status, 1);
  assert.equal(runOrange(["remember", "reject", proposalId, "--json"], cwd).status, 1);

  const second = createQuest(cwd, "remember a regression risk", {
    layer: "L2",
    clock: new Date("2026-06-16T00:02:00.000Z")
  });
  completeQuest(cwd, second.id, {
    clock: new Date("2026-06-16T00:03:00.000Z"),
    unverifiedReason: "Manual verification is not available in seed test"
  });
  const secondProposal = assertJsonCommand(
    runOrange(["remember", "propose", "--quest", second.id, "--json"], cwd),
    "remember.propose"
  ).data.proposal.id;
  const rejected = assertJsonCommand(runOrange(["remember", "reject", secondProposal, "--json"], cwd), "remember.reject");
  assert.equal(rejected.data.proposal.status, "rejected");
  assert.ok(fs.existsSync(path.join(paths.rejectedMemoryDeltaProposals, `${secondProposal}.md`)));
  assert.equal(listMemoryGraphNodes(cwd).some((node) => node.data.source_proposal === secondProposal), false);
  assert.equal(runOrange(["remember", "accept", secondProposal, "--json"], cwd).status, 1);
  assert.equal(runOrange(["remember", "reject", secondProposal, "--json"], cwd).status, 1);
});

test("remember validate supports human and JSON output for pending accepted and rejected proposals", () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);

  const pending = createMemoryProposal(cwd, "remember pending validation review");
  const human = runOrange(["remember", "validate", pending.data.id], cwd);
  assert.equal(human.status, 0);
  assert.equal(human.stderr, "");
  assert.match(human.stdout, new RegExp(`Memory proposal ${pending.data.id} is valid\\.`));

  const pendingJson = assertJsonCommand(
    runOrange(["remember", "validate", pending.data.id, "--json"], cwd),
    "remember.validate"
  );
  assert.equal(pendingJson.data.validation.valid, true);
  assert.deepEqual(pendingJson.data.validation.errors, []);
  assert.equal(pendingJson.data.proposal.status, "pending");

  acceptMemoryDelta(cwd, pending.data.id);
  const acceptedJson = assertJsonCommand(
    runOrange(["remember", "validate", pending.data.id, "--json"], cwd),
    "remember.validate"
  );
  assert.equal(acceptedJson.data.validation.valid, true);
  assert.equal(acceptedJson.data.proposal.status, "accepted");

  const toReject = createMemoryProposal(cwd, "remember rejected validation review");
  rejectMemoryDelta(cwd, toReject.data.id);
  const rejectedJson = assertJsonCommand(
    runOrange(["remember", "validate", toReject.data.id, "--json"], cwd),
    "remember.validate"
  );
  assert.equal(rejectedJson.data.validation.valid, true);
  assert.equal(rejectedJson.data.proposal.status, "rejected");
});

test("remember revise updates candidate why confidence timestamp and quality warnings", () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  const proposal = createMemoryProposal(cwd, "remember proposal review editing");
  fs.writeFileSync(
    proposal.filePath,
    stringifyFrontmatter(
      {
        ...proposal.data,
        updated_at: "2026-01-01T00:00:00.000Z"
      },
      proposal.body
    )
  );

  const candidate = assertJsonCommand(
    runOrange([
      "remember",
      "revise",
      proposal.data.id,
      "--candidate",
      "Adapters must validate and revise memory proposals before accepting them.",
      "--json"
    ], cwd),
    "remember.revise"
  );
  assert.equal(candidate.data.validation.valid, true);
  assert.deepEqual(candidate.data.revisions, ["candidate"]);
  assert.notEqual(candidate.data.proposal.updated_at, "2026-01-01T00:00:00.000Z");

  const why = assertJsonCommand(
    runOrange([
      "remember",
      "revise",
      proposal.data.id,
      "--why",
      "The review step keeps accepted memory nodes tied to explicit user approval.",
      "--json"
    ], cwd),
    "remember.revise"
  );
  assert.deepEqual(why.data.revisions, ["why"]);

  const confidence = assertJsonCommand(
    runOrange(["remember", "revise", proposal.data.id, "--confidence", "high", "--json"], cwd),
    "remember.revise"
  );
  assert.deepEqual(confidence.data.revisions, ["confidence"]);
  assert.equal(confidence.data.proposal.confidence, "high");

  const revised = readMemoryDeltaProposalFile(path.join(cwd, confidence.data.proposal.file));
  assert.equal(revised.data.confidence, "high");
  assert.match(revised.body, /Adapters must validate and revise memory proposals before accepting them\./);
  assert.match(revised.body, /The review step keeps accepted memory nodes tied to explicit user approval\./);
  assert.match(revised.body, /- Confidence: high/);

  const weak = assertJsonCommand(
    runOrange(["remember", "revise", proposal.data.id, "--candidate", "fix", "--json"], cwd),
    "remember.revise"
  );
  assert.equal(weak.data.validation.valid, true);
  assert.match(weak.data.validation.warnings.join("\n"), /Candidate Memory is very short or generic/);

  const doctor = runDoctor(cwd);
  assert.equal(doctor.ok, true);
  assert.match(doctor.warnings.join("\n"), /Candidate Memory is very short or generic/);
});

test("remember revise rejects accepted rejected and duplicate pending proposal edits", () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);

  const accepted = createMemoryProposal(cwd, "remember accepted revise protection");
  acceptMemoryDelta(cwd, accepted.data.id);
  const acceptedResult = runOrange([
    "remember",
    "revise",
    accepted.data.id,
    "--candidate",
    "Accepted proposals should not be revised.",
    "--json"
  ], cwd);
  assert.equal(acceptedResult.status, 1);
  const acceptedPayload = parseJsonOnly(acceptedResult.stdout);
  assertJsonEnvelope(acceptedPayload, false, "remember.revise");
  assert.match(acceptedPayload.error.message, /already accepted/);

  const rejected = createMemoryProposal(cwd, "remember rejected revise protection");
  rejectMemoryDelta(cwd, rejected.data.id);
  const rejectedResult = runOrange([
    "remember",
    "revise",
    rejected.data.id,
    "--candidate",
    "Rejected proposals should not be revised.",
    "--json"
  ], cwd);
  assert.equal(rejectedResult.status, 1);
  const rejectedPayload = parseJsonOnly(rejectedResult.stdout);
  assertJsonEnvelope(rejectedPayload, false, "remember.revise");
  assert.match(rejectedPayload.error.message, /already rejected/);

  const first = createMemoryProposal(cwd, "remember duplicate revise first proposal");
  const second = createMemoryProposal(cwd, "remember duplicate revise second proposal");
  const shared = "Pending proposal duplicate candidate memory should stop unsafe revise writes.";
  reviseMemoryDeltaProposal(cwd, first.data.id, { candidate: shared }, {
    clock: new Date("2026-06-16T00:10:00.000Z")
  });
  const duplicate = runOrange(["remember", "revise", second.data.id, "--candidate", shared, "--json"], cwd);
  assert.equal(duplicate.status, 1);
  const duplicatePayload = parseJsonOnly(duplicate.stdout);
  assertJsonEnvelope(duplicatePayload, false, "remember.revise");
  assert.match(duplicatePayload.error.message, new RegExp(`duplicates pending proposal ${first.data.id}`));
});

test("remember propose is idempotent for matching pending candidate memory", () => {
  const cwd = tempWorkspace();
  const paths = initWorkspace(cwd);
  const quest = createQuest(cwd, "remember duplicate proposal policy", {
    layer: "L2",
    clock: new Date("2026-06-16T00:00:00.000Z")
  });
  completeQuest(cwd, quest.id, {
    clock: new Date("2026-06-16T00:01:00.000Z"),
    evidence: ["npm test passed"]
  });

  const first = assertJsonCommand(
    runOrange(["remember", "propose", "--quest", quest.id, "--json"], cwd),
    "remember.propose"
  );
  const second = assertJsonCommand(
    runOrange(["remember", "propose", "--quest", quest.id, "--json"], cwd),
    "remember.propose"
  );

  assert.equal(first.data.duplicated, false);
  assert.equal(second.data.duplicated, true);
  assert.equal(second.data.proposal.duplicated, true);
  assert.equal(second.data.proposal.id, first.data.proposal.id);
  assert.equal(second.data.proposal.file, first.data.proposal.file);
  assert.deepEqual(
    fs.readdirSync(paths.pendingMemoryDeltaProposals).filter((name) => name.endsWith(".md")),
    [`${first.data.proposal.id}.md`]
  );
});

test("remember list filters by status type and source quest in JSON mode", () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);

  const decisionQuest = createQuest(cwd, "remember adapter contract decision", {
    layer: "L2",
    clock: new Date("2026-06-16T00:00:00.000Z")
  });
  completeQuest(cwd, decisionQuest.id, {
    clock: new Date("2026-06-16T00:01:00.000Z"),
    evidence: ["npm test passed"]
  });
  const decisionProposal = assertJsonCommand(
    runOrange(["remember", "propose", "--quest", decisionQuest.id, "--json"], cwd),
    "remember.propose"
  ).data.proposal;
  assertJsonCommand(runOrange(["remember", "accept", decisionProposal.id, "--json"], cwd), "remember.accept");

  const riskQuest = createQuest(cwd, "remember regression risk failure", {
    layer: "L2",
    clock: new Date("2026-06-16T00:02:00.000Z")
  });
  completeQuest(cwd, riskQuest.id, {
    clock: new Date("2026-06-16T00:03:00.000Z"),
    evidence: ["npm test passed"]
  });
  const riskProposal = assertJsonCommand(
    runOrange(["remember", "propose", "--quest", riskQuest.id, "--json"], cwd),
    "remember.propose"
  ).data.proposal;

  const constraintQuest = createQuest(cwd, "remember JSON contract policy must stay stable", {
    layer: "L2",
    clock: new Date("2026-06-16T00:04:00.000Z")
  });
  completeQuest(cwd, constraintQuest.id, {
    clock: new Date("2026-06-16T00:05:00.000Z"),
    evidence: ["npm test passed"]
  });
  const constraintProposal = assertJsonCommand(
    runOrange(["remember", "propose", "--quest", constraintQuest.id, "--json"], cwd),
    "remember.propose"
  ).data.proposal;

  const pending = assertJsonCommand(runOrange(["remember", "list", "--status", "pending", "--json"], cwd), "remember.list");
  assert.equal(pending.data.filters.status, "pending");
  assert.deepEqual(pending.data.proposals.map((proposal) => proposal.status), ["pending", "pending"]);
  assert.deepEqual(new Set(pending.data.proposals.map((proposal) => proposal.id)), new Set([riskProposal.id, constraintProposal.id]));

  const decision = assertJsonCommand(runOrange(["remember", "list", "--type", "decision", "--json"], cwd), "remember.list");
  assert.equal(decision.data.filters.type, "decision");
  assert.deepEqual(decision.data.proposals.map((proposal) => proposal.id), [decisionProposal.id]);

  const questFiltered = assertJsonCommand(runOrange(["remember", "list", "--quest", riskQuest.id, "--json"], cwd), "remember.list");
  assert.equal(questFiltered.data.filters.quest, riskQuest.id);
  assert.deepEqual(questFiltered.data.proposals.map((proposal) => proposal.id), [riskProposal.id]);
});

test("remember propose requires completed L2+ quest with verification state", async () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  const active = createQuest(cwd, "remember only after completion", {
    layer: "L2",
    clock: new Date("2026-06-16T00:00:00.000Z")
  });
  await assert.rejects(
    () => main(["remember", "propose", "--quest", active.id], { cwd, io: silentIo() }),
    /completed quests/
  );

  const small = createQuest(cwd, "fix one label typo", {
    layer: "L1",
    clock: new Date("2026-06-16T00:01:00.000Z")
  });
  completeQuest(cwd, small.id, {
    clock: new Date("2026-06-16T00:02:00.000Z"),
    evidence: ["manual check passed"]
  });
  await assert.rejects(
    () => main(["remember", "propose", "--quest", small.id], { cwd, io: silentIo() }),
    /disabled by default for L0\/L1/
  );
});

test("remember propose rejects external source import flags in v0.2", () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  const result = runOrange(["remember", "propose", "--from-file", "report.md", "--json"], cwd);
  assert.equal(result.status, 1);
  assert.equal(result.stderr, "");
  const payload = parseJsonOnly(result.stdout);
  assertJsonEnvelope(payload, false, "remember.propose");
  assert.match(payload.error.message, /External source memory import is a future feature/);
});

test("doctor catches memory proposal source quest and status problems", () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  const created = createQuest(cwd, "remember source quest provenance", {
    layer: "L2",
    clock: new Date("2026-06-16T00:00:00.000Z")
  });
  completeQuest(cwd, created.id, {
    clock: new Date("2026-06-16T00:01:00.000Z"),
    evidence: ["node --test passed"]
  });
  const proposal = proposeMemoryDelta(cwd, created.id, {
    clock: new Date("2026-06-16T00:02:00.000Z")
  });
  fs.writeFileSync(
    proposal.filePath,
    stringifyFrontmatter(
      {
        ...proposal.data,
        source_quest: "quest_missing"
      },
      proposal.body
    )
  );
  const result = runDoctor(cwd);
  assert.equal(result.ok, false);
  assert.match(result.errors.join("\n"), /source_quest not found: quest_missing/);
});

test("doctor warns when private .orange-hyper state is tracked by Git", () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  const init = spawnSync("git", ["init"], { cwd, encoding: "utf8" });
  assert.equal(init.status, 0);
  const add = spawnSync("git", ["add", "-f", ".orange-hyper/capsules/current.md"], {
    cwd,
    encoding: "utf8"
  });
  assert.equal(add.status, 0);

  const result = runDoctor(cwd);
  assert.equal(result.ok, true);
  const diagnostic = result.diagnostics.warnings.find((item) => item.code === "PUBLIC_MEMORY_TRACKED_PRIVATE_STATE");
  assert.ok(diagnostic);
  assert.match(diagnostic.message, /\.orange-hyper\/capsules\/current\.md is tracked by Git/);
});

test("doctor audits public memory for private paths and secret-like keywords", () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  const quest = createQuest(cwd, "audit public memory content before commit", {
    layer: "L2",
    clock: new Date("2026-06-16T00:00:00.000Z")
  });
  completeQuest(cwd, quest.id, {
    clock: new Date("2026-06-16T00:01:00.000Z"),
    evidence: [
      "local smoke passed in /Users/example/orange-hyper-smoke",
      "removed NPM_TOKEN from release notes"
    ]
  });
  const proposal = proposeMemoryDelta(cwd, quest.id, {
    clock: new Date("2026-06-16T00:02:00.000Z")
  });
  acceptMemoryDelta(cwd, proposal.data.id, {
    clock: new Date("2026-06-16T00:03:00.000Z")
  });

  const result = runDoctor(cwd);
  assert.equal(result.ok, false);
  assert.equal(result.diagnostics.warnings.some((item) => item.code === "PUBLIC_MEMORY_PRIVATE_PATH"), true);
  assert.equal(result.diagnostics.errors.some((item) => item.code === "PUBLIC_MEMORY_SECRET_LIKE_CONTENT"), true);
  assert.match(result.warnings.join("\n"), /contains private-looking \/Users\//);
  assert.match(result.errors.join("\n"), /contains secret-like keyword NPM_TOKEN/);
});

test("doctor catches proposal source quest project mismatch", () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  const proposal = createMemoryProposal(cwd, "remember source quest project boundary");
  const sourceQuest = readQuestFile(path.join(workspacePaths(cwd).completedQuests, `${proposal.data.source_quest}.md`));
  fs.writeFileSync(
    sourceQuest.filePath,
    stringifyFrontmatter(
      {
        ...sourceQuest.data,
        project_id: "project_source_other"
      },
      sourceQuest.body
    )
  );

  const result = runDoctor(cwd);
  assert.equal(result.ok, false);
  assert.match(result.errors.join("\n"), /memory proposal .* project_id .* does not match source quest .* project_id project_source_other/);
});

test("doctor warns when memory proposal updated_at is earlier than created_at", () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  const proposal = createMemoryProposal(cwd, "remember proposal timestamp ordering");
  fs.writeFileSync(
    proposal.filePath,
    stringifyFrontmatter(
      {
        ...proposal.data,
        created_at: "2026-06-16T00:02:00.000Z",
        updated_at: "2026-06-16T00:01:00.000Z"
      },
      proposal.body
    )
  );

  const result = runDoctor(cwd);
  assert.equal(result.ok, true);
  assert.match(result.warnings.join("\n"), /updated_at is earlier than created_at/);
});

test("memory proposal quality validation reports warnings and errors", () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  const shortQuest = createQuest(cwd, "fix", {
    layer: "L2",
    clock: new Date("2026-06-16T00:00:00.000Z")
  });
  completeQuest(cwd, shortQuest.id, {
    clock: new Date("2026-06-16T00:01:00.000Z"),
    evidence: ["npm test passed"]
  });
  const proposed = assertJsonCommand(
    runOrange(["remember", "propose", "--quest", shortQuest.id, "--json"], cwd),
    "remember.propose"
  );
  assert.match(proposed.data.warnings.join("\n"), /Candidate Memory is very short or generic/);
  assert.equal(runDoctor(cwd).ok, true);
  assert.match(runDoctor(cwd).warnings.join("\n"), /Candidate Memory is very short or generic/);

  const proposal = readMemoryDeltaProposalFile(path.join(cwd, proposed.data.proposal.file));
  const brokenBody = [
    "# Broken Memory Delta Proposal",
    "",
    "## Candidate Memory",
    "",
    "",
    "## Why this should be remembered",
    "",
    "",
    "## Evidence",
    "",
    "- unrelated note",
    "",
    "## Suggested Node",
    "",
    "- Type: risk"
  ].join("\n");
  fs.writeFileSync(
    proposal.filePath,
    stringifyFrontmatter(
      {
        ...proposal.data,
        confidence: "urgent"
      },
      brokenBody
    )
  );

  const doctor = runDoctor(cwd);
  assert.equal(doctor.ok, false);
  assert.match(doctor.errors.join("\n"), /invalid confidence urgent/);
  assert.match(doctor.errors.join("\n"), /Candidate Memory is empty/);
  assert.match(doctor.errors.join("\n"), /Why this should be remembered is empty/);
  assert.match(doctor.errors.join("\n"), /Evidence must reference source quest or verification information/);
  assert.match(doctor.errors.join("\n"), /Suggested Node type risk conflicts with node_type decision/);
});

test("accept creates graph node provenance and reject does not create graph nodes", () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  const config = readConfig(cwd);
  const acceptedQuest = createQuest(cwd, "remember accepted graph provenance", {
    layer: "L2",
    clock: new Date("2026-06-16T00:00:00.000Z")
  });
  completeQuest(cwd, acceptedQuest.id, {
    clock: new Date("2026-06-16T00:01:00.000Z"),
    evidence: ["npm test passed"]
  });
  const proposal = proposeMemoryDelta(cwd, acceptedQuest.id, {
    clock: new Date("2026-06-16T00:02:00.000Z")
  });
  const accepted = acceptMemoryDelta(cwd, proposal.data.id, {
    clock: new Date("2026-06-16T00:03:00.000Z")
  });
  assert.equal(accepted.node.data.source_proposal, proposal.data.id);
  assert.equal(accepted.node.data.project_id, config.project_id);
  assert.equal(accepted.node.data.project_name, config.project_name);
  assert.equal(accepted.node.data.source_quest, acceptedQuest.id);
  assert.equal(accepted.node.data.accepted_at, "2026-06-16T00:03:00.000Z");
  assert.equal(accepted.node.data.node_type, "decision");
  assert.equal(accepted.node.data.origin, "memory-delta-proposal");
  assert.match(accepted.node.data.source_proposal_hash, /^[a-f0-9]{64}$/);
  assert.equal(accepted.node.data.provenance.proposal_id, proposal.data.id);
  assert.equal(accepted.node.data.provenance.project_id, config.project_id);
  assert.equal(accepted.node.data.provenance.project_name, config.project_name);
  assert.equal(accepted.node.data.provenance.source_proposal, proposal.data.id);
  assert.equal(accepted.node.data.provenance.source_quest, acceptedQuest.id);
  assert.equal(accepted.node.data.provenance.accepted_at, "2026-06-16T00:03:00.000Z");
  assert.equal(accepted.node.data.provenance.node_type, "decision");
  assert.equal(accepted.node.data.provenance.origin, "memory-delta-proposal");
  assert.equal(accepted.node.data.provenance.source_proposal_hash, accepted.node.data.source_proposal_hash);

  const rejectedQuest = createQuest(cwd, "remember rejected proposal", {
    layer: "L2",
    clock: new Date("2026-06-16T00:04:00.000Z")
  });
  completeQuest(cwd, rejectedQuest.id, {
    clock: new Date("2026-06-16T00:05:00.000Z"),
    evidence: ["npm test passed"]
  });
  const rejectedProposal = proposeMemoryDelta(cwd, rejectedQuest.id, {
    clock: new Date("2026-06-16T00:06:00.000Z")
  });
  rejectMemoryDelta(cwd, rejectedProposal.data.id, {
    clock: new Date("2026-06-16T00:07:00.000Z")
  });
  assert.equal(listMemoryGraphNodes(cwd).some((node) => node.data.source_proposal === rejectedProposal.data.id), false);
  assert.equal(runDoctor(cwd).ok, true);
});

test("graph commands list show search and rebuild-index in human and JSON modes", () => {
  const cwd = tempWorkspace();
  const paths = initWorkspace(cwd, { projectName: "graph-cli-demo" });
  const config = readConfig(cwd);

  const accepted = createMemoryProposal(cwd, "remember durable graph usability decision", {
    proposalClock: new Date("2026-06-16T00:02:00.000Z")
  });
  const acceptedResult = assertJsonCommand(
    runOrange(["remember", "accept", accepted.data.id, "--json"], cwd),
    "remember.accept"
  );
  const nodeId = acceptedResult.data.node.id;

  const pending = createMemoryProposal(cwd, "remember pending proposal is not a graph node");
  const rejected = createMemoryProposal(cwd, "remember rejected proposal is not a graph node");
  rejectMemoryDelta(cwd, rejected.data.id);

  const humanList = runOrange(["graph", "list"], cwd);
  assert.equal(humanList.status, 0);
  assert.match(humanList.stdout, new RegExp(escapeRegExp(nodeId)));
  assert.doesNotMatch(humanList.stdout, new RegExp(escapeRegExp(pending.data.id)));
  assert.doesNotMatch(humanList.stdout, new RegExp(escapeRegExp(rejected.data.id)));

  const listed = assertJsonCommand(runOrange(["graph", "list", "--json"], cwd), "graph.list");
  assert.equal(listed.data.project.project_id, config.project_id);
  assert.equal(listed.data.project.project_name, "graph-cli-demo");
  assert.equal(listed.data.count, 1);
  assert.equal(listed.data.nodes[0].id, nodeId);
  assert.equal(listed.data.nodes[0].source_proposal, accepted.data.id);
  assert.match(listed.data.nodes[0].candidate_memory, /durable graph usability decision/);

  const humanShow = runOrange(["graph", "show", nodeId], cwd);
  assert.equal(humanShow.status, 0);
  assert.match(humanShow.stdout, /Graph node:/);
  assert.match(humanShow.stdout, /Candidate Memory:/);
  assert.match(humanShow.stdout, /Provenance:/);
  assert.match(humanShow.stdout, /durable graph usability decision/);

  const shown = assertJsonCommand(runOrange(["graph", "show", nodeId, "--json"], cwd), "graph.show");
  assert.equal(shown.data.node.id, nodeId);
  assert.match(shown.data.node.content, /## Source Proposal/);

  const humanSearch = runOrange(["graph", "search", "usability"], cwd);
  assert.equal(humanSearch.status, 0);
  assert.match(humanSearch.stdout, new RegExp(escapeRegExp(nodeId)));

  const searched = assertJsonCommand(runOrange(["graph", "search", "usability", "--json"], cwd), "graph.search");
  assert.equal(searched.data.query, "usability");
  assert.equal(searched.data.count, 1);
  assert.deepEqual(searched.data.nodes.map((node) => node.id), [nodeId]);
  assert.ok(searched.data.nodes[0].matches.includes("candidate_memory") || searched.data.nodes[0].matches.includes("title"));

  const pendingSearch = assertJsonCommand(runOrange(["graph", "search", "pending proposal", "--json"], cwd), "graph.search");
  assert.equal(pendingSearch.data.count, 0);

  const listedByType = assertJsonCommand(runOrange(["graph", "list", "--type", "decision", "--json"], cwd), "graph.list");
  assert.equal(listedByType.data.filters.type, "decision");
  assert.deepEqual(listedByType.data.nodes.map((node) => node.id), [nodeId]);

  const listedByQuest = assertJsonCommand(runOrange(["graph", "list", "--source-quest", accepted.data.source_quest, "--json"], cwd), "graph.list");
  assert.equal(listedByQuest.data.filters.source_quest, accepted.data.source_quest);
  assert.deepEqual(listedByQuest.data.nodes.map((node) => node.id), [nodeId]);

  const listedByProposal = assertJsonCommand(runOrange(["graph", "list", "--source-proposal", accepted.data.id, "--json"], cwd), "graph.list");
  assert.equal(listedByProposal.data.filters.source_proposal, accepted.data.id);
  assert.deepEqual(listedByProposal.data.nodes.map((node) => node.id), [nodeId]);

  const riskFiltered = assertJsonCommand(runOrange(["graph", "list", "--type", "risk", "--json"], cwd), "graph.list");
  assert.equal(riskFiltered.data.count, 0);

  const searchedByType = assertJsonCommand(runOrange(["graph", "search", "usability", "--type", "decision", "--json"], cwd), "graph.search");
  assert.equal(searchedByType.data.filters.type, "decision");
  assert.deepEqual(searchedByType.data.nodes.map((node) => node.id), [nodeId]);
  assert.equal(searchedByType.data.nodes[0].score > 0, true);

  const searchedByQuest = assertJsonCommand(runOrange(["graph", "search", "usability", "--source-quest", accepted.data.source_quest, "--json"], cwd), "graph.search");
  assert.equal(searchedByQuest.data.filters.source_quest, accepted.data.source_quest);
  assert.deepEqual(searchedByQuest.data.nodes.map((node) => node.id), [nodeId]);

  const humanRebuild = runOrange(["graph", "rebuild-index"], cwd);
  assert.equal(humanRebuild.status, 0);
  assert.match(humanRebuild.stdout, /Rebuilt \.orange-hyper\/graph\/index\.json with 1 node/);

  const rebuilt = assertJsonCommand(runOrange(["graph", "rebuild-index", "--json"], cwd), "graph.rebuildIndex");
  assert.equal(rebuilt.data.file, ".orange-hyper/graph/index.json");
  assert.equal(rebuilt.data.count, 1);
  assert.equal(rebuilt.data.index.project_id, config.project_id);
  assert.equal(rebuilt.data.index.nodes[0].id, nodeId);
  assert.equal(rebuilt.data.index.nodes[0].file, `.orange-hyper/graph/nodes/decision/${nodeId}.md`);
  assert.ok(fs.existsSync(paths.graphIndex));

  const firstRawIndex = fs.readFileSync(paths.graphIndex, "utf8");
  assertJsonCommand(runOrange(["graph", "rebuild-index", "--json"], cwd), "graph.rebuildIndex");
  const secondRawIndex = fs.readFileSync(paths.graphIndex, "utf8");
  assert.equal(secondRawIndex, firstRawIndex);
});

test("graph search ranking is deterministic and favors exact id/title matches", () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  const first = createMemoryProposal(cwd, "remember graph ranking exact target");
  const firstAccepted = acceptMemoryDelta(cwd, first.data.id);
  const firstId = firstAccepted.node.data.id;
  const second = createMemoryProposal(cwd, "remember graph ranking partial target");
  const secondAccepted = acceptMemoryDelta(cwd, second.data.id);
  const secondId = secondAccepted.node.data.id;

  const byExactId = assertJsonCommand(runOrange(["graph", "search", firstId, "--json"], cwd), "graph.search");
  assert.deepEqual(byExactId.data.nodes.map((node) => node.id), [firstId]);
  assert.equal(byExactId.data.nodes[0].matches.includes("id"), true);

  const firstGraph = assertJsonCommand(runOrange(["graph", "search", "graph ranking", "--json"], cwd), "graph.search");
  const secondGraph = assertJsonCommand(runOrange(["graph", "search", "graph ranking", "--json"], cwd), "graph.search");
  assert.deepEqual(
    firstGraph.data.nodes.map((node) => [node.id, node.score]),
    secondGraph.data.nodes.map((node) => [node.id, node.score])
  );
  assert.deepEqual(
    firstGraph.data.nodes.map((node) => node.id).sort(),
    [firstId, secondId].sort()
  );
});

test("graph list and search exclude cross-project nodes and doctor errors", () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  const proposal = createMemoryProposal(cwd, "remember graph boundary exclusion");
  const accepted = acceptMemoryDelta(cwd, proposal.data.id);
  fs.writeFileSync(
    accepted.node.filePath,
    stringifyFrontmatter(
      {
        ...accepted.node.data,
        project_id: "project_other",
        provenance: {
          ...accepted.node.data.provenance,
          project_id: "project_other"
        }
      },
      accepted.node.body
    )
  );

  const listed = assertJsonCommand(runOrange(["graph", "list", "--json"], cwd), "graph.list");
  assert.equal(listed.data.count, 0);
  const searched = assertJsonCommand(runOrange(["graph", "search", "boundary", "--json"], cwd), "graph.search");
  assert.equal(searched.data.count, 0);

  const doctor = runDoctor(cwd);
  assert.equal(doctor.ok, false);
  assert.match(doctor.errors.join("\n"), /graph node .* project_id project_other does not match config project_id/);
  assert.equal(doctor.diagnostics.errors.some((item) => item.code === "GRAPH_NODE_PROJECT_MISMATCH"), true);
});

test("graph legacy missing project_id nodes are excluded with warnings", () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  const proposal = createMemoryProposal(cwd, "remember legacy graph warning");
  const accepted = acceptMemoryDelta(cwd, proposal.data.id);
  /** @type {Record<string, unknown>} */
  const legacyData = { ...accepted.node.data };
  delete legacyData.project_id;
  delete legacyData.project_name;
  fs.writeFileSync(accepted.node.filePath, stringifyFrontmatter(legacyData, accepted.node.body));

  const listed = assertJsonCommand(runOrange(["graph", "list", "--json"], cwd), "graph.list");
  assert.equal(listed.data.count, 0);
  assert.match(listed.data.warnings.join("\n"), /graph node .* missing project_id/);

  const doctor = runDoctor(cwd);
  assert.equal(doctor.ok, true);
  assert.match(doctor.warnings.join("\n"), /graph node .* missing project_id/);
  assert.equal(doctor.diagnostics.warnings.some((item) => item.code === "LEGACY_PROJECT_ID_MISSING"), true);
});

test("doctor catches accepted memory graph provenance mismatch", () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  const quest = createQuest(cwd, "remember provenance mismatch detection", {
    layer: "L2",
    clock: new Date("2026-06-16T00:00:00.000Z")
  });
  completeQuest(cwd, quest.id, {
    clock: new Date("2026-06-16T00:01:00.000Z"),
    evidence: ["npm test passed"]
  });
  const proposal = proposeMemoryDelta(cwd, quest.id, {
    clock: new Date("2026-06-16T00:02:00.000Z")
  });
  const accepted = acceptMemoryDelta(cwd, proposal.data.id, {
    clock: new Date("2026-06-16T00:03:00.000Z")
  });
  fs.writeFileSync(
    accepted.node.filePath,
    stringifyFrontmatter(
      {
        ...accepted.node.data,
        project_id: "project_other",
        source_quest: "quest_other",
        origin: "manual",
        provenance: {
          ...accepted.node.data.provenance,
          project_id: "project_other",
          source_quest: "quest_other",
          origin: "manual"
        }
      },
      accepted.node.body
    )
  );

  const doctor = runDoctor(cwd);
  assert.equal(doctor.ok, false);
  assert.match(doctor.errors.join("\n"), /graph node .* project_id project_other does not match config project_id/);
  assert.match(doctor.errors.join("\n"), /graph node .* project_id project_other does not match source proposal/);
  assert.match(doctor.errors.join("\n"), /provenance does not match accepted proposal/);
  assert.match(doctor.errors.join("\n"), /origin provenance does not match memory-delta-proposal/);
});

test("doctor catches accepted graph node missing accepted source proposal file", () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  const proposal = createMemoryProposal(cwd, "remember missing accepted proposal provenance");
  const accepted = acceptMemoryDelta(cwd, proposal.data.id);
  fs.unlinkSync(accepted.proposal.filePath);

  const doctor = runDoctor(cwd);
  assert.equal(doctor.ok, false);
  assert.match(doctor.errors.join("\n"), /source_proposal .* is missing accepted proposal file/);
  const diagnostic = doctor.diagnostics.errors.find((item) => item.code === "ACCEPTED_NODE_SOURCE_PROPOSAL_MISSING");
  assert.ok(diagnostic);
  assert.match(diagnostic.message, new RegExp(escapeRegExp(accepted.node.data.source_proposal)));
  assert.equal(
    diagnostic.hint,
    "Commit accepted proposal provenance or restore the accepted proposal file. Pending/rejected proposals are local by default, but accepted proposals should be shared with accepted graph nodes."
  );
});

test("doctor catches invalid graph index JSON after memory accept", () => {
  const cwd = tempWorkspace();
  const paths = initWorkspace(cwd);
  const created = createQuest(cwd, "remember graph index validity", {
    layer: "L2",
    clock: new Date("2026-06-16T00:00:00.000Z")
  });
  completeQuest(cwd, created.id, {
    clock: new Date("2026-06-16T00:01:00.000Z"),
    evidence: ["npm test passed"]
  });
  const proposal = proposeMemoryDelta(cwd, created.id, {
    clock: new Date("2026-06-16T00:02:00.000Z")
  });
  acceptMemoryDelta(cwd, proposal.data.id, {
    clock: new Date("2026-06-16T00:03:00.000Z")
  });
  fs.writeFileSync(paths.graphIndex, "{broken");
  const result = runDoctor(cwd);
  assert.equal(result.ok, false);
  assert.match(result.errors.join("\n"), /graph\/index\.json is not valid JSON/);
});

test("doctor catches graph index mismatch orphan entries and missing graph nodes", () => {
  const cwd = tempWorkspace();
  const paths = initWorkspace(cwd);
  const proposal = createMemoryProposal(cwd, "remember graph index mismatch detection");
  const accepted = acceptMemoryDelta(cwd, proposal.data.id);
  const index = JSON.parse(fs.readFileSync(paths.graphIndex, "utf8"));
  fs.writeFileSync(
    paths.graphIndex,
    `${JSON.stringify({
      ...index,
      nodes: [
        {
          ...index.nodes[0],
          title: "Wrong title"
        },
        {
          id: "decision.orphan",
          file: ".orange-hyper/graph/nodes/decision/decision.orphan.md",
          project_id: readConfig(cwd).project_id,
          project_name: readConfig(cwd).project_name,
          node_type: "decision",
          title: "Orphan",
          source_quest: "quest_orphan",
          source_proposal: "proposal_orphan",
          accepted_at: "2026-06-16T00:00:00.000Z",
          candidate_memory: "Orphan",
          summary: "Orphan",
          tags: ["decision"],
          keywords: ["orphan"]
        }
      ]
    }, null, 2)}\n`
  );

  const mismatch = runDoctor(cwd);
  assert.equal(mismatch.ok, false);
  assert.match(mismatch.errors.join("\n"), /does not match source graph node/);
  assert.match(mismatch.errors.join("\n"), /is orphaned from source graph nodes/);
  assert.equal(mismatch.diagnostics.errors.some((item) => item.code === "GRAPH_INDEX_STALE_ENTRY" && /rebuild-index/.test(item.hint)), true);
  assert.equal(mismatch.diagnostics.errors.some((item) => item.code === "GRAPH_INDEX_ORPHAN_ENTRY" && /rebuild-index/.test(item.hint)), true);

  fs.unlinkSync(accepted.node.filePath);
  const missing = runDoctor(cwd);
  assert.equal(missing.ok, false);
  assert.match(missing.errors.join("\n"), /accepted memory proposal .* is missing graph node/);
  assert.equal(missing.diagnostics.errors.some((item) => item.code === "ACCEPTED_PROPOSAL_MISSING_NODE"), true);
});

test("graph selectors reject path traversal", async () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  const proposal = createMemoryProposal(cwd, "remember graph selector safety");
  acceptMemoryDelta(cwd, proposal.data.id);
  for (const selector of ["../../package.json", "../README.md", "decision/../../bad"]) {
    await assert.rejects(
      () => main(["graph", "show", selector], { cwd, io: silentIo() }),
      /Graph node selector must be an id, not a path/
    );
    const result = runOrange(["graph", "show", selector, "--json"], cwd);
    assert.equal(result.status, 1);
    const payload = parseJsonOnly(result.stdout);
    assertJsonEnvelope(payload, false, "graph.show");
    assert.match(payload.error.message, /must be an id, not a path/);
  }
});

test("remember selectors reject path traversal", async () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  const created = createQuest(cwd, "remember selector safety", {
    layer: "L2",
    clock: new Date("2026-06-16T00:00:00.000Z")
  });
  completeQuest(cwd, created.id, {
    clock: new Date("2026-06-16T00:01:00.000Z"),
    evidence: ["node --test passed"]
  });
  const proposal = proposeMemoryDelta(cwd, created.id, {
    clock: new Date("2026-06-16T00:02:00.000Z")
  });
  assert.ok(readMemoryDeltaProposalFile(proposal.filePath));
  for (const selector of ["../../package.json", "../README.md", "pending/../../bad"]) {
    await assert.rejects(() => main(["remember", "show", selector], { cwd, io: silentIo() }), /must be an id, not a path/);
    await assert.rejects(() => main(["remember", "validate", selector], { cwd, io: silentIo() }), /must be an id, not a path/);
    await assert.rejects(() => main(["remember", "revise", selector, "--candidate", "safe"], { cwd, io: silentIo() }), /must be an id, not a path/);
    await assert.rejects(() => main(["remember", "accept", selector], { cwd, io: silentIo() }), /must be an id, not a path/);
    await assert.rejects(() => main(["remember", "reject", selector], { cwd, io: silentIo() }), /must be an id, not a path/);
  }
});

test("identity summary includes memory proposal and accepted node counts", async () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd, { projectName: "memory-identity-demo" });
  const config = readConfig(cwd);
  const pendingQuest = createQuest(cwd, "fix", {
    layer: "L2",
    clock: new Date("2026-06-16T00:00:00.000Z")
  });
  completeQuest(cwd, pendingQuest.id, {
    clock: new Date("2026-06-16T00:01:00.000Z"),
    evidence: ["npm test passed"]
  });
  proposeMemoryDelta(cwd, pendingQuest.id, {
    clock: new Date("2026-06-16T00:02:00.000Z")
  });

  const acceptedQuest = createQuest(cwd, "remember accepted decision", {
    layer: "L2",
    clock: new Date("2026-06-16T00:03:00.000Z")
  });
  completeQuest(cwd, acceptedQuest.id, {
    clock: new Date("2026-06-16T00:04:00.000Z"),
    evidence: ["npm test passed"]
  });
  const acceptedProposal = proposeMemoryDelta(cwd, acceptedQuest.id, {
    clock: new Date("2026-06-16T00:05:00.000Z")
  });
  acceptMemoryDelta(cwd, acceptedProposal.data.id, {
    clock: new Date("2026-06-16T00:06:00.000Z")
  });

  const rejectedQuest = createQuest(cwd, "remember rejected risk", {
    layer: "L2",
    clock: new Date("2026-06-16T00:07:00.000Z")
  });
  completeQuest(cwd, rejectedQuest.id, {
    clock: new Date("2026-06-16T00:08:00.000Z"),
    evidence: ["npm test passed"]
  });
  const rejectedProposal = proposeMemoryDelta(cwd, rejectedQuest.id, {
    clock: new Date("2026-06-16T00:09:00.000Z")
  });
  rejectMemoryDelta(cwd, rejectedProposal.data.id, {
    clock: new Date("2026-06-16T00:10:00.000Z")
  });

  const { output, io } = captureIo();
  await main(["identity", "build", "--json"], { cwd, io });
  const payload = parseJsonOnly(output.join(""));
  assertJsonEnvelope(payload, true, "identity.build");
  assert.equal(payload.data.summary_file, ".orange-hyper/identity/summary.json");
  assert.equal(payload.data.summary.project_id, config.project_id);
  assert.equal(payload.data.summary.source_repository, "https://github.com/KoreanCode/orange-hyper");
  assert.equal(payload.data.summary.project_name, "memory-identity-demo");
  assert.equal(payload.data.summary.pendingMemoryProposals, 1);
  assert.equal(payload.data.summary.pendingMemoryProposalsWithWarnings, 1);
  assert.equal(payload.data.summary.acceptedMemoryProposals, 1);
  assert.equal(payload.data.summary.rejectedMemoryProposals, 1);
  assert.equal(payload.data.summary.acceptedMemoryNodes, 1);
  assert.equal(payload.data.summary.projectBoundaryActive, true);
  assert.equal(payload.data.summary.graphPreview.acceptedMemoryNodes, 1);
  assert.deepEqual(payload.data.summary.graphPreview.nodeTypeDistribution, { decision: 1 });
  assert.equal(payload.data.summary.graphPreview.readOnly, true);
  assert.equal(payload.data.summary.graphPreview.editingSupported, false);
  assert.equal(payload.data.summary.graphPreview.nodes[0].project_id, config.project_id);
  assert.match(payload.data.summary.graphPreview.nodes[0].candidate_memory, /remember accepted decision/);
  assert.deepEqual(payload.data.summary.topProposalNodeTypes, [
    { nodeType: "decision", count: 2 },
    { nodeType: "risk", count: 1 }
  ]);
  const summary = JSON.parse(fs.readFileSync(workspacePaths(cwd).identitySummaryJson, "utf8"));
  assert.equal(summary.project_id, config.project_id);
  assert.equal(summary.project_name, "memory-identity-demo");
  const html = fs.readFileSync(workspacePaths(cwd).identityHtml, "utf8");
  assert.match(html, /Accepted memory node details/);
  assert.match(html, /<meta name="source-repository" content="https:\/\/github\.com\/KoreanCode\/orange-hyper">/);
  assert.match(html, /Node ID/);
  assert.match(html, /Candidate Memory:/);
});

test("quest done --json prints completed quest information as valid JSON", async () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  const created = createQuest(cwd, "complete through JSON mode", {
    clock: new Date("2026-06-16T00:00:00.000Z")
  });
  const evidencePath = path.join(cwd, "verification.txt");
  fs.writeFileSync(evidencePath, "npm test passed\n");
  const { output, io } = captureIo();
  await main(["quest", "done", created.id, "--evidence", "git diff --check passed", "--evidence-file", "verification.txt", "--json"], { cwd, io });
  const raw = output.join("");
  const payload = parseJsonOnly(raw);
  assertJsonEnvelope(payload, true, "quest.done");
  assert.equal(payload.data.quest.id, created.id);
  assert.equal(payload.data.quest.status, "completed");
  assert.equal(payload.data.quest.verification_status, "verified");
  assert.deepEqual(payload.data.quest.verification_evidence, ["git diff --check passed", "npm test passed"]);
  assert.doesNotMatch(raw, /^Completed /m);
  assert.doesNotMatch(raw, /^Moved to /m);
  assert.doesNotMatch(raw, /^Verification status:/m);
});

test("doctor --json prints ok true diagnostics as valid JSON", async () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  const { output, io } = captureIo();
  await main(["doctor", "--json"], { cwd, io });
  const raw = output.join("");
  const payload = parseJsonOnly(raw);
  assertJsonEnvelope(payload, true, "doctor.run");
  assert.equal(payload.data.ok, true);
  assert.deepEqual(payload.data.errors, []);
  assert.doesNotMatch(raw, /^Orange doctor/m);
  assert.doesNotMatch(raw, /^No problems found\./m);
});

test("doctor --json prints ok false diagnostics and exits non-zero for invalid state", () => {
  const cwd = tempWorkspace();
  const paths = initWorkspace(cwd);
  fs.writeFileSync(path.join(paths.activeQuests, "broken.md"), "# Missing frontmatter\n");
  const result = runOrange(["doctor", "--json"], cwd);
  assert.equal(result.status, 2);
  assert.equal(result.stderr, "");
  const payload = parseJsonOnly(result.stdout);
  assertJsonEnvelope(payload, false, "doctor.run");
  assert.equal(payload.error.code, "DOCTOR_FAILED");
  assert.equal(payload.data.ok, false);
  assert.match(payload.data.errors.join("\n"), /Missing YAML frontmatter/);
});

test("doctor warns for legacy files missing project_id and reports it in JSON", () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  const quest = createQuest(cwd, "legacy quest without project identity", {
    clock: new Date("2026-06-16T00:00:00.000Z")
  });
  const legacyData = { ...quest.data };
  delete legacyData.project_id;
  delete legacyData.project_name;
  fs.writeFileSync(quest.filePath, stringifyFrontmatter(legacyData, quest.body));

  const doctor = runDoctor(cwd);
  assert.equal(doctor.ok, true);
  assert.match(doctor.warnings.join("\n"), /quest .* missing project_id \(legacy file\)/);
  assert.match(doctor.project_boundary.warnings.join("\n"), /missing project_id/);

  const payload = assertJsonCommand(runOrange(["doctor", "--json"], cwd), "doctor.run");
  assert.equal(payload.data.ok, true);
  assert.match(payload.data.project_boundary.warnings.join("\n"), /missing project_id/);
});

test("doctor errors for cross-project mismatch and reports it in JSON", () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  const quest = createQuest(cwd, "cross project quest", {
    clock: new Date("2026-06-16T00:00:00.000Z")
  });
  fs.writeFileSync(
    quest.filePath,
    stringifyFrontmatter(
      {
        ...quest.data,
        project_id: "project_other"
      },
      quest.body
    )
  );

  const doctor = runDoctor(cwd);
  assert.equal(doctor.ok, false);
  assert.match(doctor.errors.join("\n"), /project_id project_other does not match config project_id/);

  const result = runOrange(["doctor", "--json"], cwd);
  assert.equal(result.status, 2);
  const payload = parseJsonOnly(result.stdout);
  assertJsonEnvelope(payload, false, "doctor.run");
  assert.match(payload.data.project_boundary.errors.join("\n"), /project_other/);
  assert.equal(payload.data.project_boundary.diagnostics.errors.some((item) => item.code === "PROJECT_ID_MISMATCH"), true);
  assert.match(runOrange(["doctor"], cwd).stdout, /ERROR PROJECT_ID_MISMATCH:/);
});

test("doctor repair-project-id fills missing project identity without overwriting mismatches", () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  const config = readConfig(cwd);
  const proposal = createMemoryProposal(cwd, "repair missing project identity fields");
  const quest = readQuestFile(path.join(workspacePaths(cwd).completedQuests, `${proposal.data.source_quest}.md`));
  /** @type {Record<string, unknown>} */
  const legacyQuestData = { ...quest.data };
  /** @type {Record<string, unknown>} */
  const legacyProposalData = { ...proposal.data };
  delete legacyQuestData.project_id;
  delete legacyQuestData.project_name;
  delete legacyProposalData.project_id;
  delete legacyProposalData.project_name;
  fs.writeFileSync(quest.filePath, stringifyFrontmatter(legacyQuestData, quest.body));
  fs.writeFileSync(proposal.filePath, stringifyFrontmatter(legacyProposalData, proposal.body));

  const repaired = assertJsonCommand(runOrange(["doctor", "--repair-project-id", "--json"], cwd), "doctor.run");
  assert.equal(repaired.data.ok, true);
  assert.match(repaired.data.repairs.join("\n"), /added missing project identity fields/);
  assert.deepEqual(repaired.data.project_boundary.warnings, []);
  assert.equal(readQuestFile(quest.filePath).data.project_id, config.project_id);
  assert.equal(readMemoryDeltaProposalFile(proposal.filePath).data.project_id, config.project_id);

  const mismatchQuest = createQuest(cwd, "do not overwrite mismatched project id", {
    clock: new Date("2026-06-16T00:10:00.000Z")
  });
  fs.writeFileSync(
    mismatchQuest.filePath,
    stringifyFrontmatter(
      {
        ...mismatchQuest.data,
        project_id: "project_other"
      },
      mismatchQuest.body
    )
  );
  const mismatch = runOrange(["doctor", "--repair-project-id", "--json"], cwd);
  assert.equal(mismatch.status, 2);
  assert.equal(readQuestFile(mismatchQuest.filePath).data.project_id, "project_other");
  assert.match(parseJsonOnly(mismatch.stdout).data.project_boundary.errors.join("\n"), /project_other/);
});

test("identity build writes generated placeholder html", async () => {
  const cwd = tempWorkspace();
  const paths = initWorkspace(cwd, { projectName: "identity-demo" });
  const config = readConfig(cwd);
  const created = createQuest(cwd, "build identity placeholder", {
    clock: new Date("2026-06-16T00:00:00.000Z")
  });
  completeQuest(cwd, created.id, {
    clock: new Date("2026-06-16T00:01:00.000Z"),
    evidence: ["node --test passed"]
  });
  await main(["identity", "build"], { cwd, io: silentIo() });
  const html = fs.readFileSync(paths.identityHtml, "utf8");
  assert.match(html, /identity-demo/);
  assert.match(html, new RegExp(`Project ID: ${escapeRegExp(config.project_id)}`));
  assert.match(html, /Level: Seed/);
  assert.match(html, /Memory Graph Preview/);
  assert.match(html, /Graph preview is read-only\./);
  assert.match(html, /Graph editing is not supported\./);
  assert.match(html, /Accepted memory nodes are candidate project memory\./);
  assert.match(html, /Project Boundary Active/);
  assert.match(html, /Accepted memory node count:/);
  assert.match(html, /<meta name="source-repository" content="https:\/\/github\.com\/KoreanCode\/orange-hyper">/);
  assert.match(html, /orange-hyper-state/);
});

test("identity build --json prints generated html path and summary", async () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd, { projectName: "identity-json-demo" });
  const config = readConfig(cwd);
  const created = createQuest(cwd, "build identity JSON summary", {
    clock: new Date("2026-06-16T00:00:00.000Z")
  });
  completeQuest(cwd, created.id, {
    clock: new Date("2026-06-16T00:01:00.000Z"),
    evidence: ["node --test passed"]
  });
  const { output, io } = captureIo();
  await main(["identity", "build", "--json"], { cwd, io });
  const raw = output.join("");
  const payload = parseJsonOnly(raw);
  assertJsonEnvelope(payload, true, "identity.build");
  assert.equal(payload.data.file, ".orange-hyper/identity/orange-hyper.html");
  assert.equal(payload.data.summary_file, ".orange-hyper/identity/summary.json");
  assert.equal(payload.data.summary.project_id, config.project_id);
  assert.equal(payload.data.summary.source_repository, "https://github.com/KoreanCode/orange-hyper");
  assert.equal(payload.data.summary.project_name, "identity-json-demo");
  assert.equal(payload.data.summary.projectName, "identity-json-demo");
  assert.equal(payload.data.summary.completedCount, 1);
  assert.equal(payload.data.summary.verifiedCount, 1);
  assert.equal(payload.data.summary.graphPreview.readOnly, true);
  assert.equal(payload.data.summary.graphPreview.editingSupported, false);
  assert.deepEqual(payload.data.summary.graphPreview.nodeTypeDistribution, {});
  assert.equal(payload.data.summary.projectBoundaryActive, true);
  assert.deepEqual(payload.data.summary.statusMessages, [
    "Memory proposal review is active.",
    "Graph preview is read-only.",
    "Graph editing is not supported.",
    "Accepted memory nodes are candidate project memory."
  ]);
  assert.doesNotMatch(raw, /^Wrote /m);
});

test("JSON mode failures print machine-readable errors and exit non-zero", () => {
  const cwd = tempWorkspace();
  initWorkspace(cwd);
  const created = createQuest(cwd, "fail completion without evidence", {
    clock: new Date("2026-06-16T00:00:00.000Z")
  });
  const result = runOrange(["quest", "done", created.id, "--json"], cwd);
  assert.equal(result.status, 1);
  assert.equal(result.stderr, "");
  const payload = parseJsonOnly(result.stdout);
  assertJsonEnvelope(payload, false, "quest.done");
  assert.equal(payload.error.code, "USER_INPUT_ERROR");
  assert.match(payload.error.message, /requires --evidence or --unverified/);
});

test("all JSON success envelopes include contract version and dot command ids", () => {
  const cwd = tempWorkspace();
  assert.equal(runOrange(["init"], cwd).status, 0);

  const created = assertJsonCommand(
    runOrange(["quest", "new", "--json", "implement adapter contract freeze"], cwd),
    "quest.new"
  );
  const questId = created.data.quest.id;

  assertJsonCommand(runOrange(["route", "--quest", questId, "--json"], cwd), "route.show");
  assertJsonCommand(runOrange(["capsule", "--quest", questId, "--json"], cwd), "capsule.build");
  assertJsonCommand(
    runOrange(["quest", "done", questId, "--evidence", "npm test passed", "--json"], cwd),
    "quest.done"
  );
  const proposed = assertJsonCommand(runOrange(["remember", "propose", "--quest", questId, "--json"], cwd), "remember.propose");
  const proposalId = proposed.data.proposal.id;
  assertJsonCommand(runOrange(["remember", "list", "--json"], cwd), "remember.list");
  assertJsonCommand(runOrange(["remember", "show", proposalId, "--json"], cwd), "remember.show");
  assertJsonCommand(runOrange(["remember", "validate", proposalId, "--json"], cwd), "remember.validate");
  assertJsonCommand(
    runOrange([
      "remember",
      "revise",
      proposalId,
      "--candidate",
      "Adapter contract freeze is a durable project memory candidate.",
      "--json"
    ], cwd),
    "remember.revise"
  );
  const accepted = assertJsonCommand(runOrange(["remember", "accept", proposalId, "--json"], cwd), "remember.accept");
  const nodeId = accepted.data.node.id;
  assertJsonCommand(runOrange(["graph", "list", "--json"], cwd), "graph.list");
  assertJsonCommand(runOrange(["graph", "show", nodeId, "--json"], cwd), "graph.show");
  assertJsonCommand(runOrange(["graph", "search", "contract", "--json"], cwd), "graph.search");
  assertJsonCommand(runOrange(["graph", "rebuild-index", "--json"], cwd), "graph.rebuildIndex");
  assertJsonCommand(runOrange(["hook", "preview", "--json"], cwd), "hook.preview");
  assertJsonCommand(runOrange(["hook", "status", "--json"], cwd), "hook.status");
  assertJsonCommand(runOrange(["hook", "run", "session-start", "--json"], cwd), "hook.runSessionStart");
  assertJsonCommand(runOrange(["hook", "run", "stop", "--json"], cwd), "hook.runStop");

  const rejectedQuest = assertJsonCommand(
    runOrange(["quest", "new", "--json", "remember rejected adapter contract risk"], cwd),
    "quest.new"
  ).data.quest.id;
  assertJsonCommand(
    runOrange(["quest", "done", rejectedQuest, "--evidence", "npm test passed", "--json"], cwd),
    "quest.done"
  );
  const rejectedProposal = assertJsonCommand(
    runOrange(["remember", "propose", "--quest", rejectedQuest, "--json"], cwd),
    "remember.propose"
  ).data.proposal.id;
  assertJsonCommand(runOrange(["remember", "reject", rejectedProposal, "--json"], cwd), "remember.reject");
  assertJsonCommand(runOrange(["doctor", "--json"], cwd), "doctor.run");
  assertJsonCommand(runOrange(["identity", "build", "--json"], cwd), "identity.build");
});

test("README version sync check passes for all localized READMEs", () => {
  const repoRoot = path.resolve(new URL("..", import.meta.url).pathname);
  const result = spawnSync(process.execPath, ["scripts/check-readme-sync.js"], {
    cwd: repoRoot,
    encoding: "utf8"
  });
  assert.equal(result.status, 0);
  assert.match(result.stdout, /README version sync OK: 0\.4-doc\.2/);
});

function createMemoryProposal(cwd, title, options = {}) {
  const quest = createQuest(cwd, title, {
    layer: "L2",
    clock: options.questClock
  });
  completeQuest(cwd, quest.id, {
    clock: options.completedClock,
    evidence: [options.evidence || "npm test passed"]
  });
  return proposeMemoryDelta(cwd, quest.id, {
    clock: options.proposalClock
  });
}

function silentIo() {
  return {
    stdout: { write: () => {} },
    stderr: { write: () => {} }
  };
}

function parseJsonOnly(raw) {
  assert.equal(raw.trimStart().startsWith("{"), true);
  assert.equal(raw.trimEnd().endsWith("}"), true);
  return JSON.parse(raw);
}

function assertJsonCommand(result, command) {
  assert.equal(result.status, 0);
  assert.equal(result.stderr, "");
  const payload = parseJsonOnly(result.stdout);
  assertJsonEnvelope(payload, true, command);
  return payload;
}

function assertJsonEnvelope(payload, ok, command) {
  assert.equal(payload.ok, ok);
  assert.equal(payload.contract_version, JSON_CONTRACT_VERSION);
  assert.equal(payload.command, command);
  assert.match(payload.command, /^[A-Za-z0-9]+(?:\.[A-Za-z0-9]+)+$/);
}

function runOrange(args, cwd) {
  return spawnSync(process.execPath, [ORANGE_BIN.pathname, ...args], {
    cwd,
    encoding: "utf8"
  });
}

function assertGitIgnored(cwd, filePath, expectedIgnored) {
  const result = spawnSync("git", ["check-ignore", "-q", filePath], {
    cwd,
    encoding: "utf8"
  });
  if (expectedIgnored) {
    assert.equal(result.status, 0, `${filePath} should be ignored`);
  } else {
    assert.notEqual(result.status, 0, `${filePath} should not be ignored`);
  }
}

function captureIo() {
  const output = [];
  return {
    output,
    io: {
      stdout: { write: (chunk) => output.push(chunk) },
      stderr: { write: () => {} }
    }
  };
}

function escapeRegExp(value) {
  return String(value).replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
