export const ORANGE_HYPER_VERSION = "0.6.0-alpha.0";
export const ORANGE_HYPER_PROJECT_NAME = "Orange Hyper";
export const ORANGE_HYPER_PACKAGE_NAME = "orange-hyper";
export const ORANGE_HYPER_SOURCE_REPOSITORY = "https://github.com/KoreanCode/orange-hyper";
export const ORANGE_HYPER_OFFICIAL_PACKAGE = "https://www.npmjs.com/package/orange-hyper";
export const ORANGE_HYPER_LICENSE = "MIT";

export function originMetadata() {
  return {
    generated_by: ORANGE_HYPER_PROJECT_NAME,
    generator_package: ORANGE_HYPER_PACKAGE_NAME,
    generator_version: ORANGE_HYPER_VERSION,
    source_repository: ORANGE_HYPER_SOURCE_REPOSITORY,
    official_package: ORANGE_HYPER_OFFICIAL_PACKAGE,
    license: ORANGE_HYPER_LICENSE
  };
}

export function originSummaryLines() {
  return [
    `Generated by: ${ORANGE_HYPER_PROJECT_NAME} ${ORANGE_HYPER_VERSION}`,
    `Source repository: ${ORANGE_HYPER_SOURCE_REPOSITORY}`,
    `Official package: ${ORANGE_HYPER_OFFICIAL_PACKAGE}`
  ];
}
